version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - './todo-frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true   

  api:
    container_name: api
    restart: always
    build: ./todo-api
    ports:
      - "8000:8000"
    links:
      - mongo
    environment:
      - PORT=8000
      - APP_DATABASE_URL=mongo
      - APP_DATABASE_NAME=todo-list
      - NODE_ENV=development


  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"  